# Generated by Django 2.2 on 2019-04-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190416_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='NonProfit',
        ),
    ]
