# Generated by Django 2.2 on 2019-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_email', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=0)),
            ],
        ),
    ]
