# Generated by Django 2.1.7 on 2019-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='listing_time',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
