# Generated by Django 2.2 on 2019-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Claim',
        ),
    ]
