# Generated by Django 2.2 on 2019-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mondaystart', models.IntegerField(default=0)),
                ('mondayend', models.IntegerField(default=0)),
                ('tuesdaystart', models.IntegerField(default=0)),
                ('tuesdayend', models.IntegerField(default=0)),
                ('wednesdaystart', models.IntegerField(default=0)),
                ('wednesdayend', models.IntegerField(default=0)),
                ('thursdaystart', models.IntegerField(default=0)),
                ('thursdayend', models.IntegerField(default=0)),
                ('fridaystart', models.IntegerField(default=0)),
                ('fridayend', models.IntegerField(default=0)),
                ('saturdaystart', models.IntegerField(default=0)),
                ('saturdayend', models.IntegerField(default=0)),
                ('sundaystart', models.IntegerField(default=0)),
                ('sundayend', models.IntegerField(default=0)),
            ],
        ),
    ]
