# Generated by Django 2.2 on 2019-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20190419_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fridayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fridaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mondayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mondaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturdayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturdaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sundayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sundaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursdayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursdaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesdayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesdaystart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesdayend',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesdaystart',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
