# Generated by Django 2.2 on 2019-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_email', models.CharField(max_length=100)),
                ('nonprofit_email', models.CharField(max_length=100)),
                ('nonprofit_name', models.CharField(max_length=100)),
                ('dish', models.CharField(max_length=100)),
                ('servings', models.IntegerField(default=0)),
            ],
        ),
    ]
