# Generated by Django 2.1.7 on 2019-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phoneNmber',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
